/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface GovernorInterfaceInterface extends ethers.utils.Interface {
  functions: {
    "validateAction(address,string)": FunctionFragment;
    "votingCNPSupply()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "validateAction",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "votingCNPSupply",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "validateAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votingCNPSupply",
    data: BytesLike
  ): Result;

  events: {};
}

export class GovernorInterface extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: GovernorInterfaceInterface;

  functions: {
    validateAction(
      target: string,
      signature: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "validateAction(address,string)"(
      target: string,
      signature: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    votingCNPSupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    "votingCNPSupply()"(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  validateAction(
    target: string,
    signature: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "validateAction(address,string)"(
    target: string,
    signature: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  votingCNPSupply(overrides?: CallOverrides): Promise<BigNumber>;

  "votingCNPSupply()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    validateAction(
      target: string,
      signature: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "validateAction(address,string)"(
      target: string,
      signature: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    votingCNPSupply(overrides?: CallOverrides): Promise<BigNumber>;

    "votingCNPSupply()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    validateAction(
      target: string,
      signature: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "validateAction(address,string)"(
      target: string,
      signature: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    votingCNPSupply(overrides?: CallOverrides): Promise<BigNumber>;

    "votingCNPSupply()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    validateAction(
      target: string,
      signature: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "validateAction(address,string)"(
      target: string,
      signature: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    votingCNPSupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "votingCNPSupply()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
