/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface TokenAllocationInterface extends ethers.utils.Interface {
  functions: {
    "accept()": FunctionFragment;
    "accepted()": FunctionFragment;
    "allocatee()": FunctionFragment;
    "allocationCount()": FunctionFragment;
    "allocationPurposeExplanation()": FunctionFragment;
    "available()": FunctionFragment;
    "burnTokensForEmergencyShutdown(uint256)": FunctionFragment;
    "canAdministerProtocol()": FunctionFragment;
    "claim(uint256)": FunctionFragment;
    "claimed()": FunctionFragment;
    "cnp()": FunctionFragment;
    "delegate()": FunctionFragment;
    "endTime()": FunctionFragment;
    "governor()": FunctionFragment;
    "id()": FunctionFragment;
    "locked()": FunctionFragment;
    "stakeTokensForNoPriceConfidence(uint256)": FunctionFragment;
    "startTime()": FunctionFragment;
    "sweep()": FunctionFragment;
    "unstakeTokensForNoPriceConfidence(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "accept", values?: undefined): string;
  encodeFunctionData(functionFragment: "accepted", values?: undefined): string;
  encodeFunctionData(functionFragment: "allocatee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "allocationCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allocationPurposeExplanation",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "available", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "burnTokensForEmergencyShutdown",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canAdministerProtocol",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "claim", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "claimed", values?: undefined): string;
  encodeFunctionData(functionFragment: "cnp", values?: undefined): string;
  encodeFunctionData(functionFragment: "delegate", values?: undefined): string;
  encodeFunctionData(functionFragment: "endTime", values?: undefined): string;
  encodeFunctionData(functionFragment: "governor", values?: undefined): string;
  encodeFunctionData(functionFragment: "id", values?: undefined): string;
  encodeFunctionData(functionFragment: "locked", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "stakeTokensForNoPriceConfidence",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "startTime", values?: undefined): string;
  encodeFunctionData(functionFragment: "sweep", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "unstakeTokensForNoPriceConfidence",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "accept", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "accepted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allocatee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allocationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allocationPurposeExplanation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "available", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "burnTokensForEmergencyShutdown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canAdministerProtocol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cnp", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "delegate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "endTime", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "governor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "id", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "locked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakeTokensForNoPriceConfidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "startTime", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sweep", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unstakeTokensForNoPriceConfidence",
    data: BytesLike
  ): Result;

  events: {
    "Accepted()": EventFragment;
    "Claimed(uint256,uint256)": EventFragment;
    "EmergencyShutdownTokensBurned(address,uint256)": EventFragment;
    "Initialized()": EventFragment;
    "StakedTokens(address,uint256)": EventFragment;
    "Sweeped(uint256)": EventFragment;
    "UnstakedTokens(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Accepted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Claimed"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "EmergencyShutdownTokensBurned"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StakedTokens"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Sweeped"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UnstakedTokens"): EventFragment;
}

export class TokenAllocation extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: TokenAllocationInterface;

  functions: {
    accept(overrides?: Overrides): Promise<ContractTransaction>;

    "accept()"(overrides?: Overrides): Promise<ContractTransaction>;

    accepted(overrides?: CallOverrides): Promise<[boolean]>;

    "accepted()"(overrides?: CallOverrides): Promise<[boolean]>;

    allocatee(overrides?: CallOverrides): Promise<[string]>;

    "allocatee()"(overrides?: CallOverrides): Promise<[string]>;

    allocationCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    "allocationCount()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    allocationPurposeExplanation(overrides?: CallOverrides): Promise<[string]>;

    "allocationPurposeExplanation()"(
      overrides?: CallOverrides
    ): Promise<[string]>;

    available(overrides?: CallOverrides): Promise<[BigNumber]>;

    "available()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    burnTokensForEmergencyShutdown(
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "burnTokensForEmergencyShutdown(uint256)"(
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    canAdministerProtocol(overrides?: CallOverrides): Promise<[boolean]>;

    "canAdministerProtocol()"(overrides?: CallOverrides): Promise<[boolean]>;

    claim(
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "claim(uint256)"(
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    claimed(overrides?: CallOverrides): Promise<[BigNumber]>;

    "claimed()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    cnp(overrides?: CallOverrides): Promise<[string]>;

    "cnp()"(overrides?: CallOverrides): Promise<[string]>;

    delegate(overrides?: Overrides): Promise<ContractTransaction>;

    "delegate()"(overrides?: Overrides): Promise<ContractTransaction>;

    endTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    "endTime()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    governor(overrides?: CallOverrides): Promise<[string]>;

    "governor()"(overrides?: CallOverrides): Promise<[string]>;

    id(overrides?: CallOverrides): Promise<[BigNumber]>;

    "id()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    locked(overrides?: CallOverrides): Promise<[BigNumber]>;

    "locked()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    stakeTokensForNoPriceConfidence(
      countCNPToStake: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "stakeTokensForNoPriceConfidence(uint256)"(
      countCNPToStake: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    startTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    "startTime()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    sweep(overrides?: Overrides): Promise<ContractTransaction>;

    "sweep()"(overrides?: Overrides): Promise<ContractTransaction>;

    unstakeTokensForNoPriceConfidence(
      settlement: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "unstakeTokensForNoPriceConfidence(address)"(
      settlement: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  accept(overrides?: Overrides): Promise<ContractTransaction>;

  "accept()"(overrides?: Overrides): Promise<ContractTransaction>;

  accepted(overrides?: CallOverrides): Promise<boolean>;

  "accepted()"(overrides?: CallOverrides): Promise<boolean>;

  allocatee(overrides?: CallOverrides): Promise<string>;

  "allocatee()"(overrides?: CallOverrides): Promise<string>;

  allocationCount(overrides?: CallOverrides): Promise<BigNumber>;

  "allocationCount()"(overrides?: CallOverrides): Promise<BigNumber>;

  allocationPurposeExplanation(overrides?: CallOverrides): Promise<string>;

  "allocationPurposeExplanation()"(overrides?: CallOverrides): Promise<string>;

  available(overrides?: CallOverrides): Promise<BigNumber>;

  "available()"(overrides?: CallOverrides): Promise<BigNumber>;

  burnTokensForEmergencyShutdown(
    count: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "burnTokensForEmergencyShutdown(uint256)"(
    count: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  canAdministerProtocol(overrides?: CallOverrides): Promise<boolean>;

  "canAdministerProtocol()"(overrides?: CallOverrides): Promise<boolean>;

  claim(
    count: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "claim(uint256)"(
    count: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  claimed(overrides?: CallOverrides): Promise<BigNumber>;

  "claimed()"(overrides?: CallOverrides): Promise<BigNumber>;

  cnp(overrides?: CallOverrides): Promise<string>;

  "cnp()"(overrides?: CallOverrides): Promise<string>;

  delegate(overrides?: Overrides): Promise<ContractTransaction>;

  "delegate()"(overrides?: Overrides): Promise<ContractTransaction>;

  endTime(overrides?: CallOverrides): Promise<BigNumber>;

  "endTime()"(overrides?: CallOverrides): Promise<BigNumber>;

  governor(overrides?: CallOverrides): Promise<string>;

  "governor()"(overrides?: CallOverrides): Promise<string>;

  id(overrides?: CallOverrides): Promise<BigNumber>;

  "id()"(overrides?: CallOverrides): Promise<BigNumber>;

  locked(overrides?: CallOverrides): Promise<BigNumber>;

  "locked()"(overrides?: CallOverrides): Promise<BigNumber>;

  stakeTokensForNoPriceConfidence(
    countCNPToStake: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "stakeTokensForNoPriceConfidence(uint256)"(
    countCNPToStake: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  startTime(overrides?: CallOverrides): Promise<BigNumber>;

  "startTime()"(overrides?: CallOverrides): Promise<BigNumber>;

  sweep(overrides?: Overrides): Promise<ContractTransaction>;

  "sweep()"(overrides?: Overrides): Promise<ContractTransaction>;

  unstakeTokensForNoPriceConfidence(
    settlement: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "unstakeTokensForNoPriceConfidence(address)"(
    settlement: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    accept(overrides?: CallOverrides): Promise<void>;

    "accept()"(overrides?: CallOverrides): Promise<void>;

    accepted(overrides?: CallOverrides): Promise<boolean>;

    "accepted()"(overrides?: CallOverrides): Promise<boolean>;

    allocatee(overrides?: CallOverrides): Promise<string>;

    "allocatee()"(overrides?: CallOverrides): Promise<string>;

    allocationCount(overrides?: CallOverrides): Promise<BigNumber>;

    "allocationCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    allocationPurposeExplanation(overrides?: CallOverrides): Promise<string>;

    "allocationPurposeExplanation()"(
      overrides?: CallOverrides
    ): Promise<string>;

    available(overrides?: CallOverrides): Promise<BigNumber>;

    "available()"(overrides?: CallOverrides): Promise<BigNumber>;

    burnTokensForEmergencyShutdown(
      count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "burnTokensForEmergencyShutdown(uint256)"(
      count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    canAdministerProtocol(overrides?: CallOverrides): Promise<boolean>;

    "canAdministerProtocol()"(overrides?: CallOverrides): Promise<boolean>;

    claim(count: BigNumberish, overrides?: CallOverrides): Promise<void>;

    "claim(uint256)"(
      count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    claimed(overrides?: CallOverrides): Promise<BigNumber>;

    "claimed()"(overrides?: CallOverrides): Promise<BigNumber>;

    cnp(overrides?: CallOverrides): Promise<string>;

    "cnp()"(overrides?: CallOverrides): Promise<string>;

    delegate(overrides?: CallOverrides): Promise<void>;

    "delegate()"(overrides?: CallOverrides): Promise<void>;

    endTime(overrides?: CallOverrides): Promise<BigNumber>;

    "endTime()"(overrides?: CallOverrides): Promise<BigNumber>;

    governor(overrides?: CallOverrides): Promise<string>;

    "governor()"(overrides?: CallOverrides): Promise<string>;

    id(overrides?: CallOverrides): Promise<BigNumber>;

    "id()"(overrides?: CallOverrides): Promise<BigNumber>;

    locked(overrides?: CallOverrides): Promise<BigNumber>;

    "locked()"(overrides?: CallOverrides): Promise<BigNumber>;

    stakeTokensForNoPriceConfidence(
      countCNPToStake: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "stakeTokensForNoPriceConfidence(uint256)"(
      countCNPToStake: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    startTime(overrides?: CallOverrides): Promise<BigNumber>;

    "startTime()"(overrides?: CallOverrides): Promise<BigNumber>;

    sweep(overrides?: CallOverrides): Promise<void>;

    "sweep()"(overrides?: CallOverrides): Promise<void>;

    unstakeTokensForNoPriceConfidence(
      settlement: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "unstakeTokensForNoPriceConfidence(address)"(
      settlement: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    Accepted(): EventFilter;

    Claimed(count: null, available: null): EventFilter;

    EmergencyShutdownTokensBurned(
      governor: string | null,
      count: null
    ): EventFilter;

    Initialized(): EventFilter;

    StakedTokens(settlement: string | null, count: null): EventFilter;

    Sweeped(count: null): EventFilter;

    UnstakedTokens(settlement: string | null): EventFilter;
  };

  estimateGas: {
    accept(overrides?: Overrides): Promise<BigNumber>;

    "accept()"(overrides?: Overrides): Promise<BigNumber>;

    accepted(overrides?: CallOverrides): Promise<BigNumber>;

    "accepted()"(overrides?: CallOverrides): Promise<BigNumber>;

    allocatee(overrides?: CallOverrides): Promise<BigNumber>;

    "allocatee()"(overrides?: CallOverrides): Promise<BigNumber>;

    allocationCount(overrides?: CallOverrides): Promise<BigNumber>;

    "allocationCount()"(overrides?: CallOverrides): Promise<BigNumber>;

    allocationPurposeExplanation(overrides?: CallOverrides): Promise<BigNumber>;

    "allocationPurposeExplanation()"(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    available(overrides?: CallOverrides): Promise<BigNumber>;

    "available()"(overrides?: CallOverrides): Promise<BigNumber>;

    burnTokensForEmergencyShutdown(
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "burnTokensForEmergencyShutdown(uint256)"(
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    canAdministerProtocol(overrides?: CallOverrides): Promise<BigNumber>;

    "canAdministerProtocol()"(overrides?: CallOverrides): Promise<BigNumber>;

    claim(count: BigNumberish, overrides?: Overrides): Promise<BigNumber>;

    "claim(uint256)"(
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    claimed(overrides?: CallOverrides): Promise<BigNumber>;

    "claimed()"(overrides?: CallOverrides): Promise<BigNumber>;

    cnp(overrides?: CallOverrides): Promise<BigNumber>;

    "cnp()"(overrides?: CallOverrides): Promise<BigNumber>;

    delegate(overrides?: Overrides): Promise<BigNumber>;

    "delegate()"(overrides?: Overrides): Promise<BigNumber>;

    endTime(overrides?: CallOverrides): Promise<BigNumber>;

    "endTime()"(overrides?: CallOverrides): Promise<BigNumber>;

    governor(overrides?: CallOverrides): Promise<BigNumber>;

    "governor()"(overrides?: CallOverrides): Promise<BigNumber>;

    id(overrides?: CallOverrides): Promise<BigNumber>;

    "id()"(overrides?: CallOverrides): Promise<BigNumber>;

    locked(overrides?: CallOverrides): Promise<BigNumber>;

    "locked()"(overrides?: CallOverrides): Promise<BigNumber>;

    stakeTokensForNoPriceConfidence(
      countCNPToStake: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "stakeTokensForNoPriceConfidence(uint256)"(
      countCNPToStake: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    startTime(overrides?: CallOverrides): Promise<BigNumber>;

    "startTime()"(overrides?: CallOverrides): Promise<BigNumber>;

    sweep(overrides?: Overrides): Promise<BigNumber>;

    "sweep()"(overrides?: Overrides): Promise<BigNumber>;

    unstakeTokensForNoPriceConfidence(
      settlement: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "unstakeTokensForNoPriceConfidence(address)"(
      settlement: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    accept(overrides?: Overrides): Promise<PopulatedTransaction>;

    "accept()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    accepted(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "accepted()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    allocatee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "allocatee()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    allocationCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "allocationCount()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    allocationPurposeExplanation(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "allocationPurposeExplanation()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    available(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "available()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    burnTokensForEmergencyShutdown(
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "burnTokensForEmergencyShutdown(uint256)"(
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    canAdministerProtocol(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "canAdministerProtocol()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    claim(
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "claim(uint256)"(
      count: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    claimed(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "claimed()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    cnp(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "cnp()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    delegate(overrides?: Overrides): Promise<PopulatedTransaction>;

    "delegate()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    endTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "endTime()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    governor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "governor()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    id(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "id()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    locked(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "locked()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    stakeTokensForNoPriceConfidence(
      countCNPToStake: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "stakeTokensForNoPriceConfidence(uint256)"(
      countCNPToStake: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    startTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "startTime()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sweep(overrides?: Overrides): Promise<PopulatedTransaction>;

    "sweep()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    unstakeTokensForNoPriceConfidence(
      settlement: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "unstakeTokensForNoPriceConfidence(address)"(
      settlement: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
